### ISSUE TITLE
[Extension Host] Activating extension `joelday.docthis` failed:  Invalid or unexpected token

### ISSUE THREAD

**Issue by alanaasmaa** [joelday/vscode-docthis#164]
Does not work after latest update.

```
error stack:  C:\Users\AlanAasmaa\.vscode\extensions\joelday.docthis-0.6.0\node_modules\typescript\lib\typescript.js:75101
                case 68 /* AmpersandEqua
                        ^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
	at createScript (vm.js:53:10)
	at Object.runInThisContext (vm.js:95:10)
	at Module._compile (module.js:543:28)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\joelday.docthis-0.6.0\out\src\documenter.js:4:12)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\joelday.docthis-0.6.0\out\src\documenter.js:430:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
```

**Comment by TheOpenDevProject** [comment]
@alanaasmaa Could you post the source that caused this issue, thanks.

**Comment by alanaasmaa** [comment]
I dont think this issue is relevant anymore. Dont remember.
