### ISSUE TITLE
Exception thrown in 'Document This': Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by jannavarro** [joelday/vscode-docthis#73]
Platform: win32

Steps to reproduce the error:

Code excerpt that reproduces the error (optional):

Exception:
{"name":"TypeError","message":"Cannot read property 'text' of undefined","stack":"TypeError: Cannot read property 'text' of undefined\n    at NodeObject.createChildren (C:\\Users\\iRemovedThisPart\\.vscode\\extensions\\joelday.docthis-0.3.9\\node_modules\\typescript\\lib\\typescript.js:78115:72)\n    at NodeObject.getChildren (C:\\Users\\iRemovedThisPart\\.vscode\\extensions\\joelday.docthis-0.3.9\\node_modules\\typescript\\lib\\typescript.js:78167:22)\n    at findChildFunc (C:\\Users\\iRemovedThisPart\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:11)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\iRemovedThisPart\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\iRemovedThisPart\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:25)\n    at Array.forEach (native)\n    at findChildFunc (C:\\Users\\iRemovedThisPart\\.vscode\\extensions\\joelday.docthis-0.3.9\\out\\src\\utilities.js:44:25)\n    at Array.forEach (native)"}

**Comment by joelday** [comment]
@jannavarro Can you provide a code snippet that reproduces this? Thanks!

**Comment by aagavin** [comment]
I have the same issue from #74 

`  private _routeTableExists():Promise<number>{
    ............
  }
`

**Comment by joelday** [comment]
@aagavin, can you provide your tsconfig.json and your vscode settings? Thank you!

**Comment by jannavarro** [comment]
@joelday Thanks for your response. I encounter this intermittently and now it is working so I do not have a snippet to give now. If ever I encounter it again I will reopen the issue and submit the code along with my tsconfig.json and vscode settings.

**Comment by jannavarro** [comment]
Oops, I realize I shouldn't have closed this as other issues are referencing this and waiting for a resolution.

**Comment by aagavin** [comment]
## tsconfig

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

## vscode settings
```
{
	"typescript.check.workspaceVersion": false
}
```

**Comment by Devidian** [comment]
Got the same error, had some unknown object properties in my code

Example:

`item.userId`

where userId was no property of item (so it was red unterlined). I removed that code and it solved the problem!

**Comment by Devidian** [comment]
I found additional issues related to this. If you have any open document with errors, this exception is thrown. First i tried to docthis a constructor like this;

```
constructor(Database) {
		super();
		this.DB = Database;
		this.setMaxListeners(20);
	}
```

in a file with errors somewhere else. Exception was thrown. Ok then i had another open file with no errors and wanted to docThis all unDoc'ed methods => Exception was thrown. I closed the tab with that error file and tried again => yeha! it works!

**Comment by joelday** [comment]
@Devidian Well, it should definitely be resilient to this kind of stuff. This is really helpful. Thanks!

**Comment by Devidian** [comment]
Ok, seems when i `CTRL+ALD+D` often enought it still works even when throwing this error. Just as a note to workaround this issue ;)

**Comment by aagavin** [comment]
> Ok, seems when i `CTRL+ALT+D` often enought it still works even when throwing this error. Just as a note to workaround this issue ;)

I can confirm that this also works for me
