### ISSUE TITLE
Exception thrown in 'Document This': Could not find file: '/5'.

### ISSUE THREAD

**Issue by shytikov** [joelday/vscode-docthis#82]
Platform: win32

Steps to reproduce the error:

Try to run `Document This` (`Ctrl-Alt-D` + `Ctrl-Alt-D`) on document in diff mode. On that one that already commited (cannot be modified).

Code excerpt that reproduces the error (optional):

Any kind of code, that could be documented.

Exception:

{"name":"Error","message":"Could not find file: '/5'.","stack":"Error: Could not find file: '/5'.\n    at getValidSourceFile (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\node_modules\\typescript\\lib\\typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\node_modules\\typescript\\lib\\typescript.js:78983:52)\n    at Documenter._getSourceFile (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:180:24)\n    at Documenter.documentThis (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\documenter.js:49:33)\n    at runCommand (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:110:24)\n    at runCommand (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (C:\\Users\\alsh\\.vscode\\extensions\\joelday.docthis-0.3.10\\out\\src\\extension.js:109:9)\n    at c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\node\\extensionHostProcess.js:12:16738\n    at e.edit (c:\\Program Files (x86)\\Microsoft VS Code\\resources\

**Comment by WoodyWoodsta** [comment]
This error is occurring on Linux as well.

Exception:
{"name":"Error","message":"Could not find file: '/mnt/data/itdev/projects/ppro/ppro-app-project/src/app-core-module/app-tooltip/app-tooltip.es6'.","stack":"Error: Could not find file: '/mnt/data/itdev/projects/ppro/ppro-app-project/src/app-core-module/app-tooltip/app-tooltip.es6'.\n    at getValidSourceFile (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78776:23)\n    at Object.getSyntacticDiagnostics (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/node_modules/typescript/lib/typescript.js:78983:52)\n    at Documenter._getSourceFile (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:180:24)\n    at Documenter.documentThis (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/out/src/documenter.js:49:33)\n    at runCommand (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:110:24)\n    at runCommand (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:66:9)\n    at context.subscriptions.push.vs.commands.registerTextEditorCommand (/home/sean/.vscode/extensions/joelday.docthis-0.3.10/out/src/extension.js:109:9)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16738\n    at e.edit (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:14547)\n    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16704"}
